### ISSUE TITLE
Support for ServiceBus.AttachmentPlugin >=5.0.0

### ISSUE THREAD

**Issue by CasperWSchmidt** [SeanFeldman/ServiceBus.AttachmentPlugin.KeyVaultProvider#21]
Using ServiceBus.AttachmentPlugin.KeyVaultProvider 2.0.0 with ServiceBus.AttachmentPlugin 5.1.0 gives a warning when building:
 `Detected package version outside of dependency constraint: ServiceBus.AttachmentPlugin.KeyVaultProvider 2.0.0 requires ServiceBus.AttachmentPlugin (>= 4.0.0 && < 5.0.0) but version ServiceBus.AttachmentPlugin 5.1.0 was resolved.`

It would be nice to be able to use the newest versions together :)

**Comment by SeanFeldman** [comment]
Closed via https://github.com/SeanFeldman/ServiceBus.AttachmentPlugin.KeyVaultProvider/commit/0d232e0634422b11e4bd61caeb6ad616b8f32eb7
