### ISSUE TITLE
Support for Microsoft.IdentityModel.Clients.ActiveDirectory > 4.0.0

### ISSUE THREAD

**Issue by CasperWSchmidt** [SeanFeldman/ServiceBus.AttachmentPlugin.KeyVaultProvider#22]
I'm trying to use my own NuGet package wrapping this nice plugin in a Windows Service (.Net framework 4.7.2), but get the following error:
`Unable to find a version of 'Microsoft.IdentityModel.Clients.ActiveDirectory' that is compatible with 'ServiceBus.AttachmentPlugin.KeyVaultProvider 2.0.0 constraint: Microsoft.IdentityModel.Clients.ActiveDirectory (>= 3.19.2 && 4.0.0)'.`

I have version 5.2.3 of Microsoft.IdentityModel.Clients.ActiveDirectory installed and the lowest version I can pick is 4.4.1. It is installed because it is a dependency for `Microsoft.Azure.Services.AppAuthentication` (version 1.3.1) which is again a dependency for `Microsoft.Azure.ServiceBus` version 4.0.0.

**Comment by SeanFeldman** [comment]
Will update.

**Comment by SeanFeldman** [comment]
Closed via https://github.com/SeanFeldman/ServiceBus.AttachmentPlugin.KeyVaultProvider/commit/bf1cfbb1b86d0f015625272eaf718454a2d51355
